Removing credentials from uri when assembling error message
rsolr/rsolr pull request #236
Opened 2024-02-29 15:32 UTC by cgalarza

Closes #235 

The credentials in the URI are exposed in both the `RSolr::Error::Http` and in the `RSolr::Error::ConnectionRefused` classes. This is my attempt at removing the credentials from the URI while keeping the error message returned from these classes the same. 

There's some more refactoring that could happen in these error classes, but it would change the output that they return. The `RSolr::Error::ConnectionRefused` could potentially just return the URI instead of a serialized version of the request context. 
`RSolr::Error::ConnectionRefused` could also inherit from `RSolr::Error::Http` and use the same `to_s` method, but that would be an API change.

2024-02-29 15:45 UTC, jrochkind commented
Love it, thank you!  This has bugged me before too. This looks like a good solution!

I am not sure if we are meaning to be maintaning the CHANGES.txt file -- it was maintained up to 2.4.0, but doens't include an entry for most recent 2.5.0. 

I guess I'd lean to getting back on it -- can you include a patch to CHANGES to add a 2.6.0 with this change listed?  And then I can do an rsolr release, looks like I have auth to do so. 

@cgalarza I would also propose, if you are interested, adding you as at least a committer to rsolr, and probably a rubygems owner as well? The bus factor for this gem is too low.

2024-02-29 15:46 UTC, jrochkind approved these changes

2024-02-29 15:49 UTC, jrochkind requested changes
Oops, removed my "approval" since CI isn't passing. :( 

I don't have time  myself to look at why not; it is quite likely not related to your changes, unfortunately. 

I am ready to approve the actual diff in this PR.

2024-02-29 15:56 UTC, cgalarza commented
The tests are using Solr 9.5 and the fixture Solr configuration is probably not up to date with Solr 9. The name of the test class is related to `Solr 5` so not sure if the tests should be scoped to Solr 5 or if I should copy the new config set for Solr 9.

2024-02-29 19:40 UTC, jrochkind commented
I suspect the name dates from when Solr 5 was new! I don't think we need to keep testing on Solr 5, or at any rate if we haven't been I don't think we need to start now?  

I think there isn't necessarily anyone with a huge feeling of ownership and understanding of why choices were made how they were at this point -- if you have energy to do it, do what you feel best?  (perhaps in another PR, or whatever is easiest!)

2024-02-29 20:24 UTC, jcoyne commented
Perhaps we need https://github.com/rsolr/rsolr/pull/238 first.

2024-02-29 21:46 UTC, jcoyne commented
@jrochkind all tests are now passing. Will you take another look?

2024-03-01 12:28 UTC, jrochkind approved these changes

2024-03-11 14:38 UTC, cgalarza commented
Is it okay to merge my own MR?

2024-03-20 14:41 UTC, merged